### ISSUE TITLE
PUButton显示问题

### ISSUE THREAD

**Issue by TommyMerlin** [Ruris/PanuonUI#12]
在xaml中添加
```xml
<StackPanel Orientation="Horizontal" Margin="0 10 0 0" HorizontalAlignment="Center">
                <pu:PUButton x:Name="btnAdd" Click="BtnAdd_Click" Content="添加" Margin="10"/>
                <pu:PUButton x:Name="btnModify" Click="BtnModify_Click" Content="修改" Margin="10"/>
                <pu:PUButton x:Name="btnDelete" Click="BtnDelete_Click" Content="删除" Margin="10"/>
</StackPanel>
```
在设计器中还是正常的
![](https://ws1.sinaimg.cn/large/8ad8ba54ly1g1hdcalr68j209e02ewec.jpg)
实际生成的时候变成
![](https://ws1.sinaimg.cn/large/8ad8ba54ly1g1hdcx7rdaj20ac02umx0.jpg)
请问是什么原因啊？
第一次点进去会有问题，关掉再打开又恢复正常了。

**Comment by Mochengvia** [comment]
![image](https://user-images.githubusercontent.com/23360265/56403032-3b3b4c80-6292-11e9-8bee-608de3351af4.png)
如果使用了您的代码，本应如此显示。若要显示成图1的样式，需要对一些属性进行调整。您是否对基础样式进行了修改？如果有，请贴出代码。

**Comment by TommyMerlin** [comment]
请问需要修改什么属性啊？我没有对基础样式做任何修改，就是引用了dll。

**Comment by Mochengvia** [comment]
运行项目里的Browser示例项目，在页面内有属性的详细介绍和属性改变实时效果




------------------ 原始邮件 ------------------
发件人: HuYe <notifications@github.com>
发送时间: 2019年4月20日 09:08
收件人: Ruris/PanuonUI <PanuonUI@noreply.github.com>
抄送: 末城via <969954321@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[Ruris/PanuonUI] PUButton显示问题 (#12)




请问需要修改什么属性啊？我没有对基础样式做任何修改，就是引用了dll。

**Comment by TommyMerlin** [comment]
![image](https://user-images.githubusercontent.com/32566324/56718105-b9a35d00-6770-11e9-980a-1f0ca29b8bc3.png)
我是设置了样式模板，但是为什么无法同时应用到三个按钮，第一个按钮没有应用样式
![image](https://user-images.githubusercontent.com/32566324/56718383-38989580-6771-11e9-960a-29b9d146a228.png)
得在另外单独设置才有用，请问这是什么原因啊？

**Comment by Mochengvia** [comment]
![image](https://user-images.githubusercontent.com/23360265/56718782-076c9500-6772-11e9-9c03-dff454484ce2.png)
![image](https://user-images.githubusercontent.com/23360265/56718793-0b98b280-6772-11e9-8745-1326790c0fce.png)

我不知道你把样式写在了哪里，不过我随手写了一个，一切正常。

**Comment by TommyMerlin** [comment]
写在APP.xaml
![image](https://user-images.githubusercontent.com/32566324/56720969-7cda6480-6776-11e9-8005-ff83c16f7bb9.png)
那为啥第一次打开显示不出来，关掉重开又正常了。
在设计器里现实的是正常的。
