### ISSUE TITLE
PassWordBox issues

### ISSUE THREAD

**Issue by wujiayi0214** [Ruris/PanuonUI#14]
i'm interested in your project.it threw NullReferenceException at PUPasswordBox_TextInput event when I use the PasswordBox , please help me

**Comment by lawlietmax** [comment]
I already tried it, its' normal.Would you mind uploading your code?

**Comment by wujiayi0214** [comment]
I have solved this problem.We need to initialize the value of Password like this:"private string _passWord = ""; " when I binding the value

**Comment by Mochengvia** [comment]
thks , this problem has been solved. please up to date
