### ISSUE TITLE
关于PUWindow图标的问题

### ISSUE THREAD

**Issue by caoxuqiang** [Ruris/PanuonUI#18]
程序左上角的图标可以采用<pu:PUWindow.Icon><Image /></pu:PUWindow.Icon>的方式显示，但是任务栏的图标就无法显示了，不知道是不是我没有找到方法。

**Comment by Panuon** [comment]
好的，收到，下周会处理这个问题

**Comment by Mochengvia** [comment]
任务栏的图标通过右击项目，属性中设置
