### ISSUE TITLE
PagingNav 分页器BUG,当页码8页时,显示有Bug

### ISSUE THREAD

**Issue by qlmgg** [Ruris/PanuonUI#2]
![tim 20181105113110](https://user-images.githubusercontent.com/26054606/47976661-62400080-e0ee-11e8-8c5a-1c4e102a9a11.png)

**Comment by Mochengvia** [comment]
是这样设计的，两个省略号只是为了维持分页器的长度基本不变

**Comment by Mochengvia** [comment]
如果觉得不合适，您可以在PagingNav的Draw方法里对页码8进行特殊判断
