### ISSUE TITLE
ComboBox相关SelectedValuePath

### ISSUE THREAD

**Issue by ZH-UCAS** [Ruris/PanuonUI#3]
在我原来的combobox中有DisplayMemberPath="Text" SelectedValuePath="Key"
1我应该如何使用pucombobox 他无法设置SelectedValuePath="Key"
2我的binding使用ItemsSource 与SelectedItem有自己的list

**Comment by ZH-UCAS** [comment]
我的结构  public class ComplexInfoModel : ObservableObject
    {
        private String key;

        /// <summary>
        /// Key值
        /// </summary>
        public String Key
        {
            get { return key; }
            set { key = value; RaisePropertyChanged(() => Key); }
        }

        private String text;

        /// <summary>
        /// Text值
        /// </summary>
        public String Text
        {
            get { return text; }
            set { text = value; RaisePropertyChanged(() => Text); }
        }

        private String boxText;

        /// <summary>
        /// Text值
        /// </summary>
        public String BoxText
        {
            get { return boxText; }
            set { boxText = value; RaisePropertyChanged(() => BoxText); }
        }
    }

**Comment by Mochengvia** [comment]
BindingItems属性只能设置为ObservableCollection&lt;PUComboBoxItemModel&gt;类型，不能像ItemsSource属性那样设置为其他类型的集合(并且ItemsSource属性也不能适用于此控件，下一个版本将隐藏它)。
你需要将集合转化为ObservableCollection&lt;PUComboBoxItemModel&gt;，Header设置为你的Text属性，Value设置为你的Key属性，并将PUComboBox的SelectedValuePath属性设置为Value即可。
![image](https://user-images.githubusercontent.com/23360265/49139363-8fb64d80-f32c-11e8-93be-827648caa404.png)
如上图所示。
这时SelectedValue的值就是Value属性了。

今天（11.28日）修复了BindingItems属性的一些问题（与本问题无关），在使用之前建议先更新一下。

**Comment by ZH-UCAS** [comment]
好的谢谢 但是我有三个以上属性时就需要修改 PUComboBox的cs文件是这样吗~
需要对应传递值给他们

**Comment by Mochengvia** [comment]
除了改cs文件之外，也可以选择把两个集合都保留下来——当用户点击确定按钮的时候，根据当前的SelectedValue去你原先的集合中找对应的条目，来获取内容。目前只有这两个方法，我说的这个方法更适合于扩展，当然直接修改cs也不是不行

**Comment by Mochengvia** [comment]
啊对了，另一个可行的办法就是把Value属性设置为你的单个ComplexInfoModel对象，这样选择的实际SelectedValue就是你的对象了。

**Comment by ZH-UCAS** [comment]
好的吧 我明天会进行尝试~谢谢~
